version: '3'

services:
  backend:
    image: your-backend-image:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/dejanpvldb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: dejan
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: dejanpvldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dejan

  frontend:
    build:
      context: ./mw_pvl_frontend 
    ports:
      - "3000:3000"
    depends_on:
      - backend